[project]
name = "cuckoo-bananas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "discord-py",
    "pynacl>=1.5.0",
]

[tool.uv.sources]
discord-py = { git = "https://github.com/Rapptz/discord.py" }